[package]
name = "from-rs"
version = "0.1.0"
edition = "2021"

publish = false

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.12"
quote = "1.0.16"
proc-macro2 = "1.0.36"
